title: David Klotz
twitter_username: ravenmokel
twitter:
  username: ravenmokel
github_username: dklotz
# email: hmm, how to protect from spambots?
author: David Klotz
url: "https://www.davidklotz.de"
permalink: pretty
paginate: 3
paginate_path: "/blog/page/:num/"
excerpt_separator: <!--more-->
description: >- # ignore newlines until next key
  Thoughts on software engineering, technology and the rest of the world.
  Personal blog, opinions are my own.
theme: minima
header_pages:
  - fahrten.html
  - about.md
  - impressum.md
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
